name: Test / Lint

on:
  pull_request:

concurrency: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: golang lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7
        with:
          args: --tests=false
          version: latest
          only-new-issues: true
          skip-config-verify: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: test
        run: |
          make sweep testacc
        env:
          TG_API_KEY_ID: ${{ secrets.TG_API_KEY }}
          TG_API_KEY_SECRET: ${{ secrets.TG_API_KEY_SECRET }}
          TG_API_HOST: api.dev.trustgrid.io
          TG_ORG_ID: dddb37c1-f707-4a55-bb72-a5978461771a
